Setup
CastelloDev/svg-optimizer pull request #5
Opened 2019-09-04 13:50 UTC by MpiloMshengu

refractor

2019-09-04 13:55 UTC, CastelloDev submitted a review, later dismissed

2019-09-04 13:56 UTC, hvandermerwe commented on src/functions.js
> +        .then(() => console.log('Exported: '+fileName))
missing semicolon

2019-09-04 13:56 UTC, hvandermerwe commented on src/functions.js
> +    console.log('\ndirectory: '+directory);
you can rather make use of string interpolation

2019-09-04 13:57 UTC, hvandermerwe commented on src/functions.js
> +export const comparisonReport = (origonalDirectory, optimizedDirectory) => {
typo

2019-09-04 14:00 UTC, hvandermerwe commented on src/constants.js
> +export const IMPORT_DIRECTORY = './src/svgs/';
I would suggest using path.join() to set up your directories

2019-09-04 14:16 UTC, hvandermerwe requested changes
please fix

2019-09-05 07:26 UTC, hvandermerwe submitted a review, later dismissed

2019-09-05 07:30 UTC, CastelloDev approved these changes

2019-09-05 07:30 UTC, hvandermerwe approved these changes

2019-09-05 07:31 UTC, merged